import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nabver from "@/conponenst/Nabver";
import Footer from "@/conponenst/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Nabver/>
       
        {children}

        < Footer/>
        </body>
    </html>
  );
}
